// Global UI Action
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_MENU = 'OPEN_MENU';
export const OPEN_SUBMENU = 'OPEN_SUBMENU';
export const CLOSE_ALL_SUBMENU = 'CLOSE_ALL_SUBMENU';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_RANDOM_THEME = 'CHANGE_RANDOM_THEME';
export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_GRADIENT = 'CHANGE_GRADIENT';
export const CHANGE_DECO = 'CHANGE_DECO';
export const CHANGE_BG_POSITION = 'CHANGE_BG_POSITION';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';
export const LOAD_PAGE = 'LOAD_PAGE';

// Redux Form
export const INIT = 'INIT';
export const CLEAR = 'CLEAR';

// Events
export const FETCH_TIMELINE_DATA = 'FETCH_TIMELINE_DATA';
export const FETCH_COMMENT_DATA = 'FETCH_COMMENT_DATA';
export const SHOW_DETAIL_EVENT = 'SHOW_DETAIL_EVENT';
export const POST = 'POST';
export const POST_COMMENT = 'POST_COMMENT';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const COMPOSE_EVENT = 'COMPOSE_EVENT';
export const DISCARD_EVENT = 'DISCARD_EVENT';
export const SEARCH_EVENT = 'SEARCH_EVENT';

// Profile
export const COMPOSE_PROFILE_BASE = 'COMPOSE_PROFILE_BASE';
export const DISCARD_PROFILE_BASE = 'DISCARD_PROFILE_BASE';
export const COMPOSE_PROFILE_ABOUT = 'COMPOSE_PROFILE_ABOUT';
export const DISCARD_PROFILE_ABOUT = 'DISCARD_PROFILE_ABOUT';
export const COMPOSE_PROFILE_INTEREST = 'COMPOSE_PROFILE_INTEREST';
export const DISCARD_PROFILE_INTEREST = 'DISCARD_PROFILE_INTEREST';

// Contact
export const FETCH_CONTACT_DATA = 'FETCH_CONTACT_DATA';
export const SHOW_DETAIL_CONTACT = 'SHOW_DETAIL_CONTACT';
export const HIDE_DETAIL = 'HIDE_DETAIL';
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SUBMIT_CONTACT = 'SUBMIT_CONTACT';
export const CLOSE_CONTACT_FORM = 'CLOSE_CONTACT_FORM';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SEARCH_CONTACT = 'SEARCH_CONTACT';

// Chat
export const FETCH_CHAT_DATA = 'FETCH_CHAT_DATA';
export const SHOW_CHAT = 'SHOW_CHAT';
export const HIDE_CHAT = 'HIDE_CHAT';
export const SEND_CHAT = 'SEND_CHAT';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';

// Notification Form
export const CLOSE_NOTIF = 'CLOSE_NOTIF';

// authentification
export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 15;

export const EMAIL_MAX_LENGTH = 40;

export const PASSWORD_MIN_LENGTH = 6;
export const PASSWORD_MAX_LENGTH = 20;
