import imgApi from '../images/photos';
import avatarApi from '../images/avatars';
const productData = [
	{
		id: '1',
		name: 'Alison Becker',
		title: 'Cras convallis lacus orc',
		date: 'September, 12 2018',
		time: '08:01',
		thumbnail: imgApi[21],
		image: imgApi[23],
		avatar: avatarApi[6],
		desc: 'Curabitur egestas consequat lorem, vel fermentum augue porta id.',
		content: 'Curabitur egestas consequat lorem, vel fermentum augue porta id.',
		ratting: 4,
		price: 30,
		prevPrice: 0,
		discount: '',
		soldout: false,
	},
	{
		id: '2',
		name: 'Arnold TAA',
		title: 'Vivamus sit amet interdum elit',
		date: 'November, 12 2018',
		time: '08:01',
		thumbnail: imgApi[22],
		image: imgApi[22],
		avatar: avatarApi[6],
		desc: 'Maecenas nisl libero, tincidunt id odio id, feugiat vulputate quam.',
		content: 'Maecenas nisl libero, tincidunt id odio id, feugiat vulputate quam.',
		ratting: 0,
		price: 15,
		prevPrice: 150,
		discount: '90%',
		soldout: false,
	},
	{
		id: '3',
		name: 'Rivelbab',
		title: 'Fusce placerat enim et odio molestie sagittis',
		date: 'September, 12 2018',
		time: '08:01',
		thumbnail: imgApi[23],
		image: imgApi[23],
		avatar: avatarApi[6],
		desc: 'Duis tristique metus magna, lobortis aliquam risus euismod sit amet',
		content: 'Duis tristique metus magna, lobortis aliquam risus euismod sit amet',
		ratting: 5,
		price: 30,
		prevPrice: 0,
		discount: '',
		soldout: true,
	},
];

export default productData;
